export const fonts = [
  { name: "Arial", style: "Arial" },
  { name: "Verdana", style: "Verdana" },
  { name: "Times New Roman", style: "'Times New Roman'" },
  { name: "Georgia", style: "Georgia" },
  { name: "Courier New", style: "'Courier New'" },
  { name: "Tahoma", style: "Tahoma" },
  { name: "Trebuchet MS", style: "'Trebuchet MS'" },
  { name: "Comic Sans MS", style: "'Comic Sans MS'" },
  { name: "Impact", style: "Impact" },
  { name: "Lucida Console", style: "'Lucida Console'" },
  { name: "Palatino Linotype", style: "'Palatino Linotype'" },
  { name: "Segoe UI", style: "'Segoe UI'" },
  { name: "Helvetica", style: "Helvetica" },
  { name: "Gill Sans", style: "'Gill Sans'" },
  { name: "Optima", style: "Optima" },
  { name: "Futura", style: "Futura" },
  { name: "Candara", style: "Candara" },
  { name: "Garamond", style: "Garamond" },
  { name: "Bookman", style: "Bookman" },
  { name: "Franklin Gothic Medium", style: "'Franklin Gothic Medium'" },
  { name: "Brush Script MT", style: "'Brush Script MT'" },
];
