export const fonts = [
  "Arial",
  "Times New Roman",
  "Verdana",
  "Helvetica",
  "Georgia",
  "Courier New",
  "Tahoma",
  "Comic Sans MS",
  "Impact",
  "Calibri",
  "Garamond",
  "Century Gothic",
  "Arial Black",
  "Lucida Console",
  "Courier",
  "Palatino Linotype",
  "Segoe UI",
  "Trebuchet MS",
  "Futura",
  "Roboto",
];
