import { ReactElement, SVGProps } from 'react';
import { Angry, Cross, Cursor, Hand, Mark, Simile } from '@/components/svgs';

interface Sticker {
	type: 'image';
	src: ReactElement<SVGProps<SVGSVGElement>>;
}
export const stickers: Sticker[] = [
	{ type: 'image', src: <Cursor height="24px" width="24px" /> },
	{ type: 'image', src: <Hand height="24px" width="24px" /> },
	{ type: 'image', src: <Simile height="24px" width="24px" /> },
	{ type: 'image', src: <Cross height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Mark height="24px" width="24px" /> },
	{ type: 'image', src: <Cursor height="24px" width="24px" /> },
	{ type: 'image', src: <Hand height="24px" width="24px" /> },
	{ type: 'image', src: <Simile height="24px" width="24px" /> },
	{ type: 'image', src: <Cross height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Mark height="24px" width="24px" /> },
	{ type: 'image', src: <Cursor height="24px" width="24px" /> },
	{ type: 'image', src: <Hand height="24px" width="24px" /> },
	{ type: 'image', src: <Simile height="24px" width="24px" /> },
	{ type: 'image', src: <Cross height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Mark height="24px" width="24px" /> },
	{ type: 'image', src: <Cursor height="24px" width="24px" /> },
	{ type: 'image', src: <Hand height="24px" width="24px" /> },
	{ type: 'image', src: <Simile height="24px" width="24px" /> },
	{ type: 'image', src: <Cross height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Mark height="24px" width="24px" /> },
	{ type: 'image', src: <Cursor height="24px" width="24px" /> },
	{ type: 'image', src: <Hand height="24px" width="24px" /> },
	{ type: 'image', src: <Simile height="24px" width="24px" /> },
	{ type: 'image', src: <Cross height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Mark height="24px" width="24px" /> },
	{ type: 'image', src: <Cursor height="24px" width="24px" /> },
	{ type: 'image', src: <Hand height="24px" width="24px" /> },
	{ type: 'image', src: <Simile height="24px" width="24px" /> },
	{ type: 'image', src: <Cross height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Cursor height="24px" width="24px" /> },
	{ type: 'image', src: <Hand height="24px" width="24px" /> },
	{ type: 'image', src: <Simile height="24px" width="24px" /> },
	{ type: 'image', src: <Cross height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Cursor height="24px" width="24px" /> },
	{ type: 'image', src: <Hand height="24px" width="24px" /> },
	{ type: 'image', src: <Simile height="24px" width="24px" /> },
	{ type: 'image', src: <Cross height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
	{ type: 'image', src: <Angry height="24px" width="24px" /> },
];
